name: Auto Deployment to DockerHub & AWS

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
          
      - uses: actions/checkout@v2
      - name: build and release to DockerHub
        env:
          NAME: brinst07
          REPO: todowith-be
        run: |
          docker build -t $REPO .
          docker tag $REPO:latest $NAME/$REPO:latest
          docker push $NAME/$REPO:latest
          
  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Deploy in EC2
        env:
          PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.HOSTNAME }}
          USER_NAME: ${{ secrets.USER_NAME }}
          NAME: brinst07
          REPO: todowith-be
          
        run: |
          echo "${PRIVATE_KEY}" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
            sudo docker stop todowith-be
            sudo docker rm todowith-be
            sudo docker rmi brinst07/todowith-be
            sudo docker pull brinst07/todowith-be
            sudo docker run --env-file ./env.list -d -p 5000:5000 --name todowith-be brinst07/todowith-be:latest
          '
